#!/bin/bash
# start power logging

DIR="/usr/src/WindTurbine"
EXEC="$DIR/bin/turbine_power_log"

function clean(){
for PID in `/usr/bin/pgrep turbine_power`; do
	kill $PID
done
}

if [ "$1" == "start" ]; then
	clean
	$EXEC &> $DIR/logs/power_turbine_error.log &
#	/bin/echo $! > $DIR/pids/power_turbine.pid
elif [ "$1" == "stop" ]; then
	#/bin/kill $(cat $DIR/pids/power_turbine.pid)
	clean
fi
