#!/bin/bash
# start power logging

BIN="/usr/local/bin"
PID="/var/run"
LOG="/usr/local/logs"

EXEC="$BIN/turbine_power_log"

function clean(){
for PID in $(/usr/bin/pgrep turbine_power); do
	kill $PID
done
}

if [ "$1" == "start" ]; then
	clean
	$EXEC &> $LOG/power_turbine_error.log &
elif [ "$1" == "stop" ]; then
	clean
fi
