#!/bin/bash
# start power logging

DIR="/usr/src/WindTurbine"
EXEC="weather_log"
PIDFILE="$EXEC.pid"

function mypids(){
	MYPIDS=`/usr/bin/pgrep $EXEC `
}

function clean(){
for PID in `/usr/bin/pgrep $EXEC `; do
	/bin/kill $PID
done
}

if [ "$1" == "start" ]; then
	clean
	$DIR/bin/$EXEC weather $DIR/logs/$EXEC.csv
elif [ "$1" == "stop" ]; then
	#/bin/kill $(cat $DIR/pids/$PIDFILE)
	clean
fi
